# Shadowrocket: 2026-05-21 12:39:14
[General]
bypass-system = true
skip-proxy = 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16, localhost, *.local, captive.apple.com
tun-excluded-routes = 10.0.0.0/8, 100.64.0.0/10, 127.0.0.0/8, 169.254.0.0/16, 172.16.0.0/12, 192.0.0.0/24, 192.0.2.0/24, 192.88.99.0/24, 192.168.0.0/16, 198.51.100.0/24, 203.0.113.0/24, 224.0.0.0/4, 255.255.255.255/32, 239.255.255.250/32
dns-server = tls://223.5.5.5
fallback-dns-server = system,https://1.1.1.1/dns-query
# IPv6 保持禁用（除非你确实需要并已准备好 IPv6 规则）
ipv6 = false
prefer-ipv6 = false

# DNS 回退策略：避免在本地 DNS 失败时把查询通过代理走出
dns-fallback-system = false
dns-direct-system = false
dns-direct-fallback-proxy = false
icmp-auto-reply = true
always-reject-url-rewrite = false
# 私有IP应答。如果不启用该选项，域名解析返回私有IP，Shadowrocket会认为该域名被劫持而强制使用代理。
private-ip-answer = true
# 直连域名解析失败后使用代理。false表示不启用。
dns-direct-fallback-proxy = false
# 当UDP流量匹配到规则里不支持UDP转发的节点策略时重新选择回退行为，可选行为包括DIRECT、REJECT。DIRECT表示直连转发UDP流量，REJECT表示拒绝转发UDP流量。
udp-policy-not-supported-behaviour = REJECT

[Rule]
# AI 服务
RULE-SET,https://raw.githubusercontent.com/oopsunix/scripts/main/rules/ai.list,PROXY
# 直连
RULE-SET,https://raw.githubusercontent.com/oopsunix/scripts/main/rules/direct.list,DIRECT
# 代理
RULE-SET,https://raw.githubusercontent.com/oopsunix/scripts/main/rules/proxy.list,PROXY
# Steam 服务
RULE-SET,https://raw.githubusercontent.com/oopsunix/scripts/main/rules/steam.list,PROXY

# Advert 广告屏蔽
DOMAIN-SET,https://anti-ad.net/surge2.txt,REJECT
# Global 全球加速
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list,PROXY
# China  国内直连
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/China/China.list,DIRECT

GEOIP,CN,DIRECT
FINAL,PROXY

[Host]
# 域名解析配置 - 自定义特定域名的 DNS 解析设置
*.apple.com = server:system
*.icloud.com = server:system
*.cdn-apple.com = server:system
*.mzstatic.com = server:system

[URL Rewrite]
# URL 重写规则 - 重定向或拦截特定网址请求
^https?://(www.)?g.cn https://www.google.com 302
^https?://(www.)?google.cn https://www.google.com 302

# - Safari 内输入 命令 + 空格 + 关键词 快速指定搜索引擎搜索
# 注：先进入设置更改 Safari 默认搜索为 DuckDuckGO
# gh   (GitHub)
^https:\/\/duckduckgo.com\/\?q=gh\+([^&]+).+ https://github.com/search?q=$1 302
# wiki  (维基百科)
^https:\/\/duckduckgo.com\/\?q=wiki(\+|%20)([^&]+).+ http://wikipedia.org/wiki/$2 302
# tf  (Google 搜索 TestFlight)
^https:\/\/duckduckgo.com\/\?q=tf(\+|%20)([^&]+).+ https://www.google.com/search?as_q=$2&as_sitesearch=testflight.apple.com 302

# 无指令: 谷歌
^https:\/\/duckduckgo.com\/\?q=([^&]+).+ https://www.google.com/search?q=$1 302
# bi: 必应
^https:\/\/duckduckgo.com\/\?q=bi\+([^&]+).+ https://cn.bing.com/search?q=$1 302
# bli (哔哩哔哩) 
^https:\/\/duckduckgo.com\/\?q=bli\+([^&]+).+ https://m.bilibili.com/search?keyword=$1 302
# ytb  (YouTube)
^https:\/\/duckduckgo.com\/\?q=ytb\+([^&]+).+ https://www.youtube.com/results?search_query=$1 302
# ph  (PornHub) 
^https:\/\/duckduckgo.com\/\?q=ph\+([^&]+).+ https://cn.pornhub.com/video/search?search=$1 302